### ISSUE TITLE
Cannot get super user access

### ISSUE THREAD

**Issue by mischasworld** [xmikos/SnooperStopper#1]
Hello,

Thanks for your great tool, this really fills the gap between a safe encrypted and a everyday easy to use device.

Unfortunately I can't change the encryption password on my maguro galaxy nexus device.
When I try to change my encryption password I get the message cannot get super access 
For  a short time the root access symbol lights up and disappears.

Snooper Stopper is listed in the device admin list. My nexus (which runs on slim rom lollipop) asked me whether I would like to give root access to snooper stopper and I agreed.

I'd really like to help to fix this bug so I can use your tool.

Many greetings

Michael

**Comment by xmikos** [comment]
I think the problem is in SELinux policy. SELinux policy in Android 5 is much more strict and SnooperStopper has to inject SELinux rules to allow *vdc* to communicate with it. It supports opensource _sepolicy-inject_ (and also closed source _supolicy_ - part of _SuperSU_) for this task. You can get _sepolicy-inject_ util from here: https://github.com/xmikos/setools-android

Build it with Android NDK and copy _sepolicy-inject_ binary to _/system/xbin_ directory on the phone. If you can't build it, you can get prebuilt binary from here: http://forum.xda-developers.com/devdb/project/?id=7245#downloads (but I am afraid version there is too old, tomorrow I will upload newer binary)

**Comment by mischasworld** [comment]
Thanks for your fast reply!

I managed to change the password directly with vdc and a superuserterminal. The reboot after 3 mistypped gestures is working.

I'll try it with your new binary and leave feedback here once you uploaded it.

**Comment by mischasworld** [comment]
Me Again ;-)

Just compiled my first app with Android NDK (thought this was more complicated), now it's working. Thanks a lot for your support!

**Comment by licaon-kter** [comment]
So this is not fixable on the app side?

I'm seeing it in CM13 w/ SuperSU.
